### ISSUE TITLE
Filtering by price incorrectly

### ISSUE THREAD

**Issue by ghost** [internship-guidance/fundamentals#4]
Currently filtering by price uses from `current` to `max` prices, which makes no sense. Regarding price, filter from `min` to `current` should be applied.

**NB!** Test should be adjusted as well, so that they pass.

**Comment by vm1000** [comment]
I have an issue here. Changed price range in viewController and in unit test also with refreshing new possible values, but when testing then "expected result did not match".


<img width="1440" alt="Screenshot 2019-05-21 at 10 07 57" src="https://user-images.githubusercontent.com/41584015/58075866-71316080-7bb1-11e9-93aa-e8cda3303533.png">

**Comment by esesmuedgars** [comment]
It means that there are no cars that match all filters. In this case they are definitely cars passing through previous filters up till price. So, if there are no cars in this price range, increase price filter upper bound. And if only makes sense that you might have to change some objects in `expectedCars` array.

**Comment by vm1000** [comment]
It doesn't help. also time to time an error appears intestYearAndPriceSlider..
If I did correctly, when updated price range from min - currentVal and also added to expectedCars cars that match price range and year?

<img width="1440" alt="Screenshot 2019-05-21 at 10 46 36" src="https://user-images.githubusercontent.com/41584015/58077951-472e6d00-7bb6-11e9-915f-59dc942f9fa3.png">
<img width="1440" alt="Screenshot 2019-05-21 at 10 46 40" src="https://user-images.githubusercontent.com/41584015/58077952-472e6d00-7bb6-11e9-95f7-09f51bd0cf54.png">

**Comment by esesmuedgars** [comment]
I don't know, if'd really have to look into it. But both errors are due to changes You made, but did not update `allCars` and/or `expectedCars` correctly. Use debugging - add break points and `po` where errors **Filtered result item at index: 1 did not match year expectation.** appear. And You'll see that the error is due to `allCars` first item doesn't have same parameters (investigate `Array` extension at the bottom to know which parameters are the ones compared) when comparing to `expectedCars`.

**NB!** Car objects creation is not random in any way, and regarding to `price` requires some calculations to figure out which objects would be pipelining through. Therefore, which objects must be created and which are expected.

**Comment by ghost** [comment]
🦜
